version: '2'

services:
    db:
        image: mysql:5.7
        volumes:
            - "./docker/.data/db:/var/lib/mysql"
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ${SYMFONY_APP_PATH}/vendor/bin/:/var/www/bin
            - ./docker/logs/symfony:/var/www/symfony/var/log
        depends_on:
            - db
        stdin_open: true
        env_file:
            - ./.env
    nginx:
        build: docker/nginx
        ports:
            - ${NGINX_PORT}:80
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
