<?php

namespace App\Entity\Media;

use App\Entity\Extra\HasUuid;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Ramsey\Uuid\Uuid;
use Sonata\MediaBundle\Entity\BaseMedia;
use App\Entity\Extra\Groups as SerializationGroups;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @ORM\Entity
 * @ORM\Table(name="sonata_media")
 */
class Media extends BaseMedia
{
    use HasUuid;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Serializer\Groups({SerializationGroups::SHORT,SerializationGroups::MEDIA})
     */
    private $originName;

    public function __construct()
    {
        $this->uuid = Uuid::uuid4()->toString();
    }

    /**
     * @Serializer\VirtualProperty()
     * @Serializer\SerializedName("href")
     * @Serializer\Groups({SerializationGroups::SHORT,SerializationGroups::MEDIA,SerializationGroups::UPCOMING_EVENTS})
     * @Serializer\Type("string")
     */
    public function _href(){}

    /**
     * @Serializer\VirtualProperty()
     * @Serializer\SerializedName("href_thumbnail")
     * @Serializer\Groups({SerializationGroups::SHORT,SerializationGroups::MEDIA,SerializationGroups::UPCOMING_EVENTS})
     * @Serializer\Type("string")
     */
    public function _href_thumbnail()
    {
    }

    public function getId()
    {
        return $this->id;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash($hash): Media
    {
        $this->hash = $hash;

        return $this;
    }

    /**
     * @return string
     */
    public function getOriginName(): ?string
    {
        return $this->originName;
    }

    /**
     * @param string $originName
     * @return Media
     */
    public function setOriginName(string $originName): Media
    {
        $this->originName = $originName;

        return $this;
    }
}
