#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

gns_data_filter_doc:
  resource: "@GnsFilterBundle/Controller"
  prefix: /gns

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

admin_controllers:
  resource: ../src/Controller/Admin
  type: annotation
  prefix: /admin

security:
  resource: ../src/Controller/Security
  type: annotation
  prefix: /
